name: deploy-me
'on':
    - push
jobs:
    deploy-me:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
              env:
                  ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
            - run: |
                  cd lib
                  git config --global user.email "narender2031@gmail.com"
                  git config --global user.name "narender2031"
                  git config --global credential.helper cache
                  git clone https://${{secrets.ACCESS_TOKEN}}@github.com/narender2031/posthog-js
                  cp -r posthog-js/. clonedFolder/
                  cd clonedFolder
                  npm install
                  npm run build
                  git add .
                  git commit -m "$(date)"
                  git push